/* Generated by Yosys 0.29+23 (git sha1 cdeef5481, gcc 7.5.0-3ubuntu1~18.04 -fPIC -Os) */

(* hdlname = "\\packetizer_fsm" *)
(* src = "packetizer_fsm.v:1.1-110.10" *)
module \$paramod\packetizer_fsm\BAUD_DIVISOR=s32'00000000000000000000000000000101 (clk, rst, fifo_empty, tx_ready, fifo_data, serial_out, tx_busy, rd_en);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire [7:0] _030_;
  wire [3:0] _031_;
  wire [1:0] _032_;
  wire [1:0] _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire [1:0] _038_;
  wire _039_;
  wire [2:0] _040_;
  wire [1:0] _041_;
  wire _042_;
  wire [1:0] _043_;
  wire _044_;
  wire [1:0] _045_;
  wire _046_;
  wire [1:0] _047_;
  wire _048_;
  wire [1:0] _049_;
  wire _050_;
  wire [1:0] _051_;
  wire _052_;
  wire [2:0] _053_;
  wire [1:0] _054_;
  wire _055_;
  (* src = "packetizer_fsm.v:35.21-35.53" *)
  wire _056_;
  (* src = "packetizer_fsm.v:65.25-65.36" *)
  wire _057_;
  wire [3:0] _058_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [11:0] _059_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [11:0] _060_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [2:0] _061_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [3:0] _062_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [3:0] _063_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [14:0] _064_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [14:0] _065_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:573.22-573.23" *)
  wire [4:0] _066_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire [2:0] _067_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire [2:0] _068_;
  wire [2:0] _069_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:571.28-571.29" *)
  wire [2:0] _070_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:583.28-583.35" *)
  wire [2:0] _071_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:575.21-575.22" *)
  wire _072_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:578.19-578.22" *)
  wire _073_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "15" *)
  wire [31:0] _074_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _075_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "16" *)
  wire [31:0] _076_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:96.44-96.59|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3" *)
  wire [31:0] _077_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:96.44-96.59|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _078_;
  (* force_downto = 32'd1 *)
  (* src = "packetizer_fsm.v:96.44-96.59|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4" *)
  wire [31:0] _079_;
  (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)
  wire _080_;
  (* src = "packetizer_fsm.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:157.2-184.5" *)
  (* unused_bits = "1 3 5 7" *)
  wire [7:0] _081_;
  (* src = "packetizer_fsm.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:157.2-184.5" *)
  (* unused_bits = "1 2 3 5 6 7" *)
  wire [7:0] _082_;
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _083_;
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _084_;
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _085_;
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _086_;
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _087_;
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _088_;
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _089_;
  (* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _090_;
  (* src = "packetizer_fsm.v:22.16-22.28" *)
  reg [15:0] baud_counter = 16'h0000;
  (* src = "packetizer_fsm.v:25.9-25.18" *)
  reg baud_tick;
  (* src = "packetizer_fsm.v:23.15-23.26" *)
  reg [3:0] bit_counter = 4'h0;
  (* src = "packetizer_fsm.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "packetizer_fsm.v:24.15-24.23" *)
  reg [7:0] data_reg = 8'h00;
  (* src = "packetizer_fsm.v:8.17-8.26" *)
  input [7:0] fifo_data;
  wire [7:0] fifo_data;
  (* src = "packetizer_fsm.v:6.11-6.21" *)
  input fifo_empty;
  wire fifo_empty;
  (* src = "packetizer_fsm.v:11.16-11.21" *)
  output rd_en;
  reg rd_en;
  (* src = "packetizer_fsm.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "packetizer_fsm.v:9.16-9.26" *)
  output serial_out;
  reg serial_out;
  (* src = "packetizer_fsm.v:21.15-21.20" *)
  reg [2:0] state = 3'h0;
  (* src = "packetizer_fsm.v:10.16-10.23" *)
  output tx_busy;
  reg tx_busy;
  (* src = "packetizer_fsm.v:7.11-7.19" *)
  input tx_ready;
  wire tx_ready;
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (_012_) rd_en <= 1'h0;
    else rd_en <= tx_ready;
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) serial_out <= 1'h1;
    else if (_000_) serial_out <= _072_;
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) tx_busy <= 1'h0;
    else if (!_025_) tx_busy <= _054_[0];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[0] <= 1'h0;
    else baud_counter[0] <= _075_[0];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[1] <= 1'h0;
    else baud_counter[1] <= _076_[1];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[2] <= 1'h0;
    else baud_counter[2] <= _076_[2];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[3] <= 1'h0;
    else baud_counter[3] <= _076_[3];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[4] <= 1'h0;
    else baud_counter[4] <= _076_[4];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[5] <= 1'h0;
    else baud_counter[5] <= _076_[5];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[6] <= 1'h0;
    else baud_counter[6] <= _076_[6];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[7] <= 1'h0;
    else baud_counter[7] <= _076_[7];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[8] <= 1'h0;
    else baud_counter[8] <= _076_[8];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[9] <= 1'h0;
    else baud_counter[9] <= _076_[9];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[10] <= 1'h0;
    else baud_counter[10] <= _076_[10];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[11] <= 1'h0;
    else baud_counter[11] <= _076_[11];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[12] <= 1'h0;
    else baud_counter[12] <= _076_[12];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[13] <= 1'h0;
    else baud_counter[13] <= _076_[13];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[14] <= 1'h0;
    else baud_counter[14] <= _076_[14];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_013_) baud_counter[15] <= 1'h0;
    else baud_counter[15] <= _076_[15];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) state[0] <= 1'h0;
    else if (_010_) state[0] <= _067_[0];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) state[1] <= 1'h0;
    else if (_010_) state[1] <= _067_[1];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) state[2] <= 1'h0;
    else if (_010_) state[2] <= _067_[2];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) bit_counter[0] <= 1'h0;
    else if (_011_) bit_counter[0] <= _062_[0];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) bit_counter[1] <= 1'h0;
    else if (_011_) bit_counter[1] <= _062_[1];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) bit_counter[2] <= 1'h0;
    else if (_011_) bit_counter[2] <= _062_[2];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) bit_counter[3] <= 1'h0;
    else if (_011_) bit_counter[3] <= _062_[3];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) data_reg[0] <= 1'h0;
    else if (!_015_) data_reg[0] <= fifo_data[0];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) data_reg[1] <= 1'h0;
    else if (!_015_) data_reg[1] <= fifo_data[1];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) data_reg[2] <= 1'h0;
    else if (!_015_) data_reg[2] <= fifo_data[2];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) data_reg[3] <= 1'h0;
    else if (!_015_) data_reg[3] <= fifo_data[3];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) data_reg[4] <= 1'h0;
    else if (!_015_) data_reg[4] <= fifo_data[4];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) data_reg[5] <= 1'h0;
    else if (!_015_) data_reg[5] <= fifo_data[5];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) data_reg[6] <= 1'h0;
    else if (!_015_) data_reg[6] <= fifo_data[6];
  (* src = "packetizer_fsm.v:48.5-109.8" *)
  always @(posedge clk)
    if (rst) data_reg[7] <= 1'h0;
    else if (!_015_) data_reg[7] <= fifo_data[7];
  (* src = "packetizer_fsm.v:28.5-45.8" *)
  always @(posedge clk)
    if (_014_) baud_tick <= 1'h0;
    else baud_tick <= _056_;
  assign _016_ = ~state[2];
  assign _018_ = ~bit_counter[1];
  assign _020_ = ~state[0];
  assign _078_[0] = ~bit_counter[0];
  assign _022_ = ~bit_counter[2];
  assign _023_ = ~baud_counter[2];
  assign _019_ = ~state[1];
  assign _075_[0] = ~baud_counter[0];
  assign _024_ = ~baud_tick;
  assign _071_[0] = _061_[2] | _066_[0];
  assign _028_ = _024_ | _053_[1];
  assign _005_ = _028_ | _021_;
  assign _006_ = _054_[0] | _025_;
  assign _030_[0] = baud_counter[0] |(* src = "packetizer_fsm.v:35.21-35.53" *)  baud_counter[1];
  assign _030_[1] = _023_ |(* src = "packetizer_fsm.v:35.21-35.53" *)  baud_counter[3];
  assign _030_[2] = baud_counter[4] |(* src = "packetizer_fsm.v:35.21-35.53" *)  baud_counter[5];
  assign _030_[3] = baud_counter[6] |(* src = "packetizer_fsm.v:35.21-35.53" *)  baud_counter[7];
  assign _030_[4] = baud_counter[8] |(* src = "packetizer_fsm.v:35.21-35.53" *)  baud_counter[9];
  assign _030_[5] = baud_counter[10] |(* src = "packetizer_fsm.v:35.21-35.53" *)  baud_counter[11];
  assign _030_[6] = baud_counter[12] |(* src = "packetizer_fsm.v:35.21-35.53" *)  baud_counter[13];
  assign _030_[7] = baud_counter[14] |(* src = "packetizer_fsm.v:35.21-35.53" *)  baud_counter[15];
  assign _031_[0] = _030_[0] |(* src = "packetizer_fsm.v:35.21-35.53" *)  _030_[1];
  assign _031_[1] = _030_[2] |(* src = "packetizer_fsm.v:35.21-35.53" *)  _030_[3];
  assign _031_[2] = _030_[4] |(* src = "packetizer_fsm.v:35.21-35.53" *)  _030_[5];
  assign _031_[3] = _030_[6] |(* src = "packetizer_fsm.v:35.21-35.53" *)  _030_[7];
  assign _032_[0] = _031_[0] |(* src = "packetizer_fsm.v:35.21-35.53" *)  _031_[1];
  assign _032_[1] = _031_[2] |(* src = "packetizer_fsm.v:35.21-35.53" *)  _031_[3];
  assign _055_ = _032_[0] |(* src = "packetizer_fsm.v:35.21-35.53" *)  _032_[1];
  assign _002_ = baud_tick | _017_;
  assign _033_[0] = _078_[0] |(* src = "packetizer_fsm.v:93.29-93.45" *)  _018_;
  assign _033_[1] = _022_ |(* src = "packetizer_fsm.v:93.29-93.45" *)  bit_counter[3];
  assign _027_ = _033_[0] |(* src = "packetizer_fsm.v:93.29-93.45" *)  _033_[1];
  assign _003_ = baud_tick | _021_;
  assign _004_ = baud_tick | _026_;
  assign _034_ = _071_[0] | _061_[0];
  assign _000_ = _034_ | _061_[1];
  assign _012_ = rst | _015_;
  assign _035_ = _020_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *)  state[1];
  assign _015_ = _035_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *)  state[2];
  assign _001_ = tx_ready | _015_;
  assign _017_ = _029_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *)  _016_;
  assign _036_ = _020_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *)  _019_;
  assign _021_ = _036_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *)  state[2];
  assign _037_ = state[0] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *)  _019_;
  assign _026_ = _037_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *)  state[2];
  assign _038_[0] = _066_[3] | _066_[0];
  assign _039_ = _038_[0] | _038_[1];
  assign _007_ = _039_ | _061_[2];
  assign _040_[0] = _005_ & _006_;
  assign _040_[1] = _002_ & _003_;
  assign _040_[2] = _004_ & _001_;
  assign _041_[0] = _040_[0] & _040_[1];
  assign _041_[1] = _040_[2] & _007_;
  assign _010_ = _041_[0] & _041_[1];
  assign _042_ = _024_ | _027_;
  assign _008_ = _042_ | _021_;
  assign _009_ = _038_[1] | _061_[2];
  assign _043_[0] = _003_ & _004_;
  assign _043_[1] = _008_ & _009_;
  assign _011_ = _043_[0] & _043_[1];
  assign _044_ = rst | _056_;
  assign _013_ = _044_ | _061_[2];
  assign _014_ = rst | _061_[2];
  assign _063_[3] = _060_[3] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _060_[7];
  assign _063_[2] = _060_[2] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _060_[7];
  assign _063_[1] = _060_[1] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _060_[7];
  assign _063_[0] = _060_[0] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _060_[7];
  assign _038_[1] = _061_[0] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _061_[1];
  assign _045_[0] = _065_[2] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _065_[5];
  assign _045_[1] = _060_[7] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _065_[11];
  assign _046_ = _045_[0] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _045_[1];
  assign _068_[2] = _046_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _065_[14];
  assign _047_[1] = _065_[7] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _065_[10];
  assign _048_ = _047_[0] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _047_[1];
  assign _068_[1] = _048_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _065_[14];
  assign _047_[0] = _065_[2] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _065_[4];
  assign _049_[1] = _065_[7] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _065_[11];
  assign _050_ = _047_[0] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _049_[1];
  assign _068_[0] = _050_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _065_[12];
  assign _051_[0] = _066_[0] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _061_[0];
  assign _051_[1] = _061_[1] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _066_[3];
  assign _052_ = _051_[0] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _051_[1];
  assign _080_ = _052_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.15" *)  _061_[2];
  assign _073_ = _071_[0] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:593.20-593.31" *)  _071_[1];
  assign _029_ = state[0] |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *)  state[1];
  assign _025_ = _029_ |(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *)  state[2];
  assign _056_ = ~(* src = "packetizer_fsm.v:35.21-35.53" *) _055_;
  assign _057_ = ~(* src = "packetizer_fsm.v:65.25-65.36" *) fifo_empty;
  assign _053_[1] = ~(* src = "packetizer_fsm.v:93.29-93.45" *) _027_;
  assign _066_[3] = ~(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *) _015_;
  assign _066_[0] = ~(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *) _017_;
  assign _061_[0] = ~(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *) _021_;
  assign _061_[1] = ~(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20" *) _026_;
  assign _054_[0] = _057_ &(* src = "packetizer_fsm.v:65.25-65.48" *)  tx_ready;
  assign _058_[0] = _027_ ? (* src = "packetizer_fsm.v:93.29-93.45|packetizer_fsm.v:93.25-97.28" *) _078_[0] : 1'hx;
  assign _058_[1] = _027_ ? (* src = "packetizer_fsm.v:93.29-93.45|packetizer_fsm.v:93.25-97.28" *) _079_[1] : 1'hx;
  assign _058_[2] = _027_ ? (* src = "packetizer_fsm.v:93.29-93.45|packetizer_fsm.v:93.25-97.28" *) _079_[2] : 1'hx;
  assign _058_[3] = _027_ ? (* src = "packetizer_fsm.v:93.29-93.45|packetizer_fsm.v:93.25-97.28" *) _079_[3] : 1'hx;
  assign _059_[0] = baud_tick ? (* src = "packetizer_fsm.v:92.25-92.34|packetizer_fsm.v:92.21-98.24" *) _058_[0] : 1'hx;
  assign _059_[1] = baud_tick ? (* src = "packetizer_fsm.v:92.25-92.34|packetizer_fsm.v:92.21-98.24" *) _058_[1] : 1'hx;
  assign _059_[2] = baud_tick ? (* src = "packetizer_fsm.v:92.25-92.34|packetizer_fsm.v:92.21-98.24" *) _058_[2] : 1'hx;
  assign _059_[3] = baud_tick ? (* src = "packetizer_fsm.v:92.25-92.34|packetizer_fsm.v:92.21-98.24" *) _058_[3] : 1'hx;
  assign _059_[7] = baud_tick ? (* src = "packetizer_fsm.v:103.25-103.34|packetizer_fsm.v:103.21-105.24" *) 1'h0 : 1'hx;
  assign _069_[1] = _027_ ? (* src = "packetizer_fsm.v:93.29-93.45|packetizer_fsm.v:93.25-97.28" *) 1'hx : 1'h0;
  assign _069_[2] = _027_ ? (* src = "packetizer_fsm.v:93.29-93.45|packetizer_fsm.v:93.25-97.28" *) 1'hx : 1'h1;
  assign _064_[4] = baud_tick ? (* src = "packetizer_fsm.v:92.25-92.34|packetizer_fsm.v:92.21-98.24" *) _069_[1] : 1'hx;
  assign _064_[5] = baud_tick ? (* src = "packetizer_fsm.v:92.25-92.34|packetizer_fsm.v:92.21-98.24" *) _069_[2] : 1'hx;
  assign _064_[7] = baud_tick ? (* src = "packetizer_fsm.v:82.25-82.34|packetizer_fsm.v:82.21-85.24" *) 1'h1 : 1'hx;
  assign _064_[11] = tx_ready ? (* src = "packetizer_fsm.v:74.25-74.33|packetizer_fsm.v:74.21-77.24" *) 1'h0 : 1'hx;
  assign _064_[10] = tx_ready ? (* src = "packetizer_fsm.v:74.25-74.33|packetizer_fsm.v:74.21-77.24" *) 1'h1 : 1'hx;
  assign _064_[12] = _054_[0] ? (* src = "packetizer_fsm.v:65.25-65.48|packetizer_fsm.v:65.21-68.24" *) 1'h1 : 1'hx;
  assign _064_[14] = _054_[0] ? (* src = "packetizer_fsm.v:65.25-65.48|packetizer_fsm.v:65.21-68.24" *) 1'h0 : 1'hx;
  assign _081_[0] = bit_counter[0] ? (* src = "packetizer_fsm.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:178.4-183.7|/usr/local/bin/../share/yosys/techmap.v:178.8-178.12" *) data_reg[1] : data_reg[0];
  assign _081_[2] = bit_counter[0] ? (* src = "packetizer_fsm.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:178.4-183.7|/usr/local/bin/../share/yosys/techmap.v:178.8-178.12" *) data_reg[3] : data_reg[2];
  assign _081_[4] = bit_counter[0] ? (* src = "packetizer_fsm.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:178.4-183.7|/usr/local/bin/../share/yosys/techmap.v:178.8-178.12" *) data_reg[5] : data_reg[4];
  assign _081_[6] = bit_counter[0] ? (* src = "packetizer_fsm.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:178.4-183.7|/usr/local/bin/../share/yosys/techmap.v:178.8-178.12" *) data_reg[7] : data_reg[6];
  assign _082_[0] = bit_counter[1] ? (* src = "packetizer_fsm.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:178.4-183.7|/usr/local/bin/../share/yosys/techmap.v:178.8-178.12" *) _081_[2] : _081_[0];
  assign _082_[4] = bit_counter[1] ? (* src = "packetizer_fsm.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:178.4-183.7|/usr/local/bin/../share/yosys/techmap.v:178.8-178.12" *) _081_[6] : _081_[4];
  assign _070_[1] = bit_counter[2] ? (* src = "packetizer_fsm.v:0.0-0.0|/usr/local/bin/../share/yosys/techmap.v:178.4-183.7|/usr/local/bin/../share/yosys/techmap.v:178.8-178.12" *) _082_[4] : _082_[0];
  assign _062_[0] = _009_ ? (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _063_[0] : 1'hx;
  assign _062_[1] = _009_ ? (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _063_[1] : 1'hx;
  assign _062_[2] = _009_ ? (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _063_[2] : 1'hx;
  assign _062_[3] = _009_ ? (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _063_[3] : 1'hx;
  assign _067_[0] = _080_ ? (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _068_[0] : 1'hx;
  assign _067_[1] = _080_ ? (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _068_[1] : 1'hx;
  assign _067_[2] = _080_ ? (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _068_[2] : 1'hx;
  assign _072_ = _000_ ? (* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:597.13-597.25" *) _073_ : 1'hx;
  assign _061_[2] = ~_025_;
  assign _060_[0] = _059_[0] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[0];
  assign _060_[1] = _059_[1] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[0];
  assign _060_[2] = _059_[2] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[0];
  assign _060_[3] = _059_[3] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[0];
  assign _065_[12] = _064_[12] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[2];
  assign _065_[14] = _064_[14] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[2];
  assign _065_[11] = _064_[11] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _066_[3];
  assign _065_[10] = _064_[10] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _066_[3];
  assign _065_[7] = _064_[7] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[1];
  assign _060_[7] = _059_[7] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[1];
  assign _065_[4] = _064_[4] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[0];
  assign _065_[5] = _064_[5] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[0];
  assign _065_[2] = _059_[7] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _066_[0];
  assign _071_[1] = _070_[1] &(* src = "packetizer_fsm.v:0.0-0.0|packetizer_fsm.v:59.13-107.20|/usr/local/bin/../share/yosys/techmap.v:585.44-585.84" *)  _061_[0];
  assign _076_[1] = baud_counter[1] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  baud_counter[0];
  assign _076_[2] = baud_counter[2] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[1];
  assign _076_[3] = baud_counter[3] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[2];
  assign _076_[4] = baud_counter[4] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[3];
  assign _076_[5] = baud_counter[5] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[4];
  assign _076_[6] = baud_counter[6] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[5];
  assign _076_[7] = baud_counter[7] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[6];
  assign _076_[8] = baud_counter[8] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[7];
  assign _076_[9] = baud_counter[9] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[8];
  assign _076_[10] = baud_counter[10] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[9];
  assign _076_[11] = baud_counter[11] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[10];
  assign _076_[12] = baud_counter[12] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[11];
  assign _076_[13] = baud_counter[13] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[12];
  assign _076_[14] = baud_counter[14] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[13];
  assign _076_[15] = baud_counter[15] ^(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _074_[14];
  assign _079_[1] = bit_counter[1] ^(* src = "packetizer_fsm.v:96.44-96.59|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  bit_counter[0];
  assign _079_[2] = bit_counter[2] ^(* src = "packetizer_fsm.v:96.44-96.59|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _077_[1];
  assign _079_[3] = bit_counter[3] ^(* src = "packetizer_fsm.v:96.44-96.59|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _077_[2];
  assign _074_[1] = baud_counter[1] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  baud_counter[0];
  assign _074_[3] = _083_ &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _074_[1];
  assign _074_[7] = _089_ &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _074_[3];
  assign _083_ = baud_counter[3] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  baud_counter[2];
  assign _084_ = baud_counter[5] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  baud_counter[4];
  assign _085_ = baud_counter[7] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  baud_counter[6];
  assign _086_ = baud_counter[9] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  baud_counter[8];
  assign _087_ = baud_counter[11] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  baud_counter[10];
  assign _088_ = baud_counter[13] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  baud_counter[12];
  assign _089_ = _085_ &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _084_;
  assign _090_ = _087_ &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _086_;
  assign _074_[11] = _090_ &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[7];
  assign _074_[5] = _084_ &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[3];
  assign _074_[9] = _086_ &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[7];
  assign _074_[13] = _088_ &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[11];
  assign _074_[2] = baud_counter[2] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[1];
  assign _074_[4] = baud_counter[4] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[3];
  assign _074_[6] = baud_counter[6] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[5];
  assign _074_[8] = baud_counter[8] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[7];
  assign _074_[10] = baud_counter[10] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[9];
  assign _074_[12] = baud_counter[12] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[11];
  assign _074_[14] = baud_counter[14] &(* src = "packetizer_fsm.v:39.37-39.53|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _074_[13];
  assign _077_[1] = bit_counter[1] &(* src = "packetizer_fsm.v:96.44-96.59|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  bit_counter[0];
  assign _077_[2] = bit_counter[2] &(* src = "packetizer_fsm.v:96.44-96.59|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _077_[1];
  assign _049_[0] = _047_[0];
  assign { _053_[2], _053_[0] } = { _021_, _024_ };
  assign _054_[1] = _025_;
  assign { _059_[11:8], _059_[6:4] } = { 4'h0, _059_[7], _059_[7], _059_[7] };
  assign { _060_[11:8], _060_[6:4] } = { 4'h0, _060_[7], _060_[7], _060_[7] };
  assign { _064_[13], _064_[9:8], _064_[6], _064_[3:0] } = { _064_[14], _064_[11], _059_[7], _064_[7], _064_[4], _059_[7], _059_[7], _059_[7] };
  assign { _065_[13], _065_[9:8], _065_[6], _065_[3], _065_[1:0] } = { _065_[14], _065_[11], _060_[7], _065_[7], _065_[4], _065_[2], _065_[2] };
  assign { _066_[4], _066_[2:1] } = _061_;
  assign _069_[0] = _069_[1];
  assign { _070_[2], _070_[0] } = 2'h1;
  assign _071_[2] = 1'h0;
  assign { _074_[31:16], _074_[0] } = { 16'h0000, baud_counter[0] };
  assign _075_[31:1] = { 16'h0000, baud_counter[15:1] };
  assign { _076_[31:16], _076_[0] } = { 15'h0000, _074_[15], _075_[0] };
  assign { _077_[31:4], _077_[0] } = { 28'h0000000, bit_counter[0] };
  assign _078_[31:1] = { 28'h0000000, bit_counter[3:1] };
  assign { _079_[31:4], _079_[0] } = { 27'h0000000, _077_[3], _078_[0] };
endmodule

(* dynports =  1  *)
(* src = "fifo.v:1.1-46.10" *)
module fifo(clk, rst, wr_en, rd_en, data_in, data_out, full, empty);
  (* src = "fifo.v:24.5-45.8" *)
  wire [3:0] _000_;
  (* src = "fifo.v:24.5-45.8" *)
  wire [7:0] _001_;
  (* src = "fifo.v:24.5-45.8" *)
  wire [7:0] _002_;
  (* src = "fifo.v:24.5-45.8" *)
  wire [3:0] _003_;
  (* src = "fifo.v:24.5-45.8" *)
  wire [7:0] _004_;
  (* src = "fifo.v:24.5-45.8" *)
  wire [7:0] _005_;
  wire [7:0] _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire [1:0] _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  (* src = "fifo.v:39.17-39.32" *)
  wire _040_;
  wire [7:0] _041_;
  wire [7:0] _042_;
  wire [7:0] _043_;
  wire [7:0] _044_;
  wire [7:0] _045_;
  wire [7:0] _046_;
  wire [7:0] _047_;
  wire [7:0] _048_;
  wire [7:0] _049_;
  wire [7:0] _050_;
  wire [7:0] _051_;
  wire [7:0] _052_;
  wire [7:0] _053_;
  wire [7:0] _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire [4:0] _071_;
  wire [4:0] _072_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3 4" *)
  wire [31:0] _073_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "4" *)
  wire [31:0] _074_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4 5" *)
  wire [31:0] _075_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4" *)
  wire [31:0] _076_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _077_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "5" *)
  wire [31:0] _078_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:41.27-41.37|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "3 4" *)
  wire [31:0] _079_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:41.27-41.37|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  (* unused_bits = "4" *)
  wire [31:0] _080_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:41.27-41.37|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "4 5" *)
  wire [31:0] _081_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:274.23-274.25" *)
  (* unused_bits = "4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _082_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [31:0] _083_;
  (* force_downto = 32'd1 *)
  (* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:270.26-270.27" *)
  (* unused_bits = "5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31" *)
  wire [31:0] _084_;
  (* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _085_;
  (* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _086_;
  (* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _087_;
  (* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _088_;
  (* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _089_;
  (* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _090_;
  (* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _091_;
  (* src = "fifo.v:6.11-6.14" *)
  input clk;
  wire clk;
  (* src = "fifo.v:19.24-19.29" *)
  reg [4:0] count = 5'h00;
  (* src = "fifo.v:10.28-10.35" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "fifo.v:11.33-11.41" *)
  output [7:0] data_out;
  reg [7:0] data_out;
  (* src = "fifo.v:13.12-13.17" *)
  output empty;
  wire empty;
  (* src = "fifo.v:12.12-12.16" *)
  output full;
  wire full;
  reg [7:0] \mem[0] ;
  reg [7:0] \mem[10] ;
  reg [7:0] \mem[11] ;
  reg [7:0] \mem[12] ;
  reg [7:0] \mem[13] ;
  reg [7:0] \mem[14] ;
  reg [7:0] \mem[15] ;
  reg [7:0] \mem[1] ;
  reg [7:0] \mem[2] ;
  reg [7:0] \mem[3] ;
  reg [7:0] \mem[4] ;
  reg [7:0] \mem[5] ;
  reg [7:0] \mem[6] ;
  reg [7:0] \mem[7] ;
  reg [7:0] \mem[8] ;
  reg [7:0] \mem[9] ;
  (* src = "fifo.v:9.11-9.16" *)
  input rd_en;
  wire rd_en;
  (* init = 5'hx0 *)
  (* src = "fifo.v:18.24-18.30" *)
  (* unused_bits = "4" *)
  wire [4:0] rd_ptr;
  (* src = "fifo.v:7.11-7.14" *)
  input rst;
  wire rst;
  (* src = "fifo.v:8.11-8.16" *)
  input wr_en;
  wire wr_en;
  (* init = 5'hx0 *)
  (* src = "fifo.v:17.24-17.30" *)
  (* unused_bits = "4" *)
  wire [4:0] wr_ptr;
  always @(posedge clk)
    if (rst) data_out[0] <= 1'h0;
    else if (_040_) data_out[0] <= _006_[0];
  always @(posedge clk)
    if (rst) data_out[1] <= 1'h0;
    else if (_040_) data_out[1] <= _006_[1];
  always @(posedge clk)
    if (rst) data_out[2] <= 1'h0;
    else if (_040_) data_out[2] <= _006_[2];
  always @(posedge clk)
    if (rst) data_out[3] <= 1'h0;
    else if (_040_) data_out[3] <= _006_[3];
  always @(posedge clk)
    if (rst) data_out[4] <= 1'h0;
    else if (_040_) data_out[4] <= _006_[4];
  always @(posedge clk)
    if (rst) data_out[5] <= 1'h0;
    else if (_040_) data_out[5] <= _006_[5];
  always @(posedge clk)
    if (rst) data_out[6] <= 1'h0;
    else if (_040_) data_out[6] <= _006_[6];
  always @(posedge clk)
    if (rst) data_out[7] <= 1'h0;
    else if (_040_) data_out[7] <= _006_[7];
  always @(posedge clk)
    if (_060_) \mem[14] [0] <= _001_[0];
  always @(posedge clk)
    if (_060_) \mem[14] [1] <= _001_[1];
  always @(posedge clk)
    if (_060_) \mem[14] [2] <= _001_[2];
  always @(posedge clk)
    if (_060_) \mem[14] [3] <= _001_[3];
  always @(posedge clk)
    if (_060_) \mem[14] [4] <= _001_[4];
  always @(posedge clk)
    if (_060_) \mem[14] [5] <= _001_[5];
  always @(posedge clk)
    if (_060_) \mem[14] [6] <= _001_[6];
  always @(posedge clk)
    if (_060_) \mem[14] [7] <= _001_[7];
  always @(posedge clk)
    if (_059_) \mem[13] [0] <= _001_[0];
  always @(posedge clk)
    if (_059_) \mem[13] [1] <= _001_[1];
  always @(posedge clk)
    if (_059_) \mem[13] [2] <= _001_[2];
  always @(posedge clk)
    if (_059_) \mem[13] [3] <= _001_[3];
  always @(posedge clk)
    if (_059_) \mem[13] [4] <= _001_[4];
  always @(posedge clk)
    if (_059_) \mem[13] [5] <= _001_[5];
  always @(posedge clk)
    if (_059_) \mem[13] [6] <= _001_[6];
  always @(posedge clk)
    if (_059_) \mem[13] [7] <= _001_[7];
  always @(posedge clk)
    if (_058_) \mem[12] [0] <= _001_[0];
  always @(posedge clk)
    if (_058_) \mem[12] [1] <= _001_[1];
  always @(posedge clk)
    if (_058_) \mem[12] [2] <= _001_[2];
  always @(posedge clk)
    if (_058_) \mem[12] [3] <= _001_[3];
  always @(posedge clk)
    if (_058_) \mem[12] [4] <= _001_[4];
  always @(posedge clk)
    if (_058_) \mem[12] [5] <= _001_[5];
  always @(posedge clk)
    if (_058_) \mem[12] [6] <= _001_[6];
  always @(posedge clk)
    if (_058_) \mem[12] [7] <= _001_[7];
  always @(posedge clk)
    if (_057_) \mem[11] [0] <= _001_[0];
  always @(posedge clk)
    if (_057_) \mem[11] [1] <= _001_[1];
  always @(posedge clk)
    if (_057_) \mem[11] [2] <= _001_[2];
  always @(posedge clk)
    if (_057_) \mem[11] [3] <= _001_[3];
  always @(posedge clk)
    if (_057_) \mem[11] [4] <= _001_[4];
  always @(posedge clk)
    if (_057_) \mem[11] [5] <= _001_[5];
  always @(posedge clk)
    if (_057_) \mem[11] [6] <= _001_[6];
  always @(posedge clk)
    if (_057_) \mem[11] [7] <= _001_[7];
  always @(posedge clk)
    if (_056_) \mem[10] [0] <= _001_[0];
  always @(posedge clk)
    if (_056_) \mem[10] [1] <= _001_[1];
  always @(posedge clk)
    if (_056_) \mem[10] [2] <= _001_[2];
  always @(posedge clk)
    if (_056_) \mem[10] [3] <= _001_[3];
  always @(posedge clk)
    if (_056_) \mem[10] [4] <= _001_[4];
  always @(posedge clk)
    if (_056_) \mem[10] [5] <= _001_[5];
  always @(posedge clk)
    if (_056_) \mem[10] [6] <= _001_[6];
  always @(posedge clk)
    if (_056_) \mem[10] [7] <= _001_[7];
  always @(posedge clk)
    if (_055_) \mem[0] [0] <= _001_[0];
  always @(posedge clk)
    if (_055_) \mem[0] [1] <= _001_[1];
  always @(posedge clk)
    if (_055_) \mem[0] [2] <= _001_[2];
  always @(posedge clk)
    if (_055_) \mem[0] [3] <= _001_[3];
  always @(posedge clk)
    if (_055_) \mem[0] [4] <= _001_[4];
  always @(posedge clk)
    if (_055_) \mem[0] [5] <= _001_[5];
  always @(posedge clk)
    if (_055_) \mem[0] [6] <= _001_[6];
  always @(posedge clk)
    if (_055_) \mem[0] [7] <= _001_[7];
  always @(posedge clk)
    if (_069_) \mem[8] [0] <= _001_[0];
  always @(posedge clk)
    if (_069_) \mem[8] [1] <= _001_[1];
  always @(posedge clk)
    if (_069_) \mem[8] [2] <= _001_[2];
  always @(posedge clk)
    if (_069_) \mem[8] [3] <= _001_[3];
  always @(posedge clk)
    if (_069_) \mem[8] [4] <= _001_[4];
  always @(posedge clk)
    if (_069_) \mem[8] [5] <= _001_[5];
  always @(posedge clk)
    if (_069_) \mem[8] [6] <= _001_[6];
  always @(posedge clk)
    if (_069_) \mem[8] [7] <= _001_[7];
  always @(posedge clk)
    if (_068_) \mem[7] [0] <= _001_[0];
  always @(posedge clk)
    if (_068_) \mem[7] [1] <= _001_[1];
  always @(posedge clk)
    if (_068_) \mem[7] [2] <= _001_[2];
  always @(posedge clk)
    if (_068_) \mem[7] [3] <= _001_[3];
  always @(posedge clk)
    if (_068_) \mem[7] [4] <= _001_[4];
  always @(posedge clk)
    if (_068_) \mem[7] [5] <= _001_[5];
  always @(posedge clk)
    if (_068_) \mem[7] [6] <= _001_[6];
  always @(posedge clk)
    if (_068_) \mem[7] [7] <= _001_[7];
  always @(posedge clk)
    if (_067_) \mem[6] [0] <= _001_[0];
  always @(posedge clk)
    if (_067_) \mem[6] [1] <= _001_[1];
  always @(posedge clk)
    if (_067_) \mem[6] [2] <= _001_[2];
  always @(posedge clk)
    if (_067_) \mem[6] [3] <= _001_[3];
  always @(posedge clk)
    if (_067_) \mem[6] [4] <= _001_[4];
  always @(posedge clk)
    if (_067_) \mem[6] [5] <= _001_[5];
  always @(posedge clk)
    if (_067_) \mem[6] [6] <= _001_[6];
  always @(posedge clk)
    if (_067_) \mem[6] [7] <= _001_[7];
  always @(posedge clk)
    if (_066_) \mem[5] [0] <= _001_[0];
  always @(posedge clk)
    if (_066_) \mem[5] [1] <= _001_[1];
  always @(posedge clk)
    if (_066_) \mem[5] [2] <= _001_[2];
  always @(posedge clk)
    if (_066_) \mem[5] [3] <= _001_[3];
  always @(posedge clk)
    if (_066_) \mem[5] [4] <= _001_[4];
  always @(posedge clk)
    if (_066_) \mem[5] [5] <= _001_[5];
  always @(posedge clk)
    if (_066_) \mem[5] [6] <= _001_[6];
  always @(posedge clk)
    if (_066_) \mem[5] [7] <= _001_[7];
  always @(posedge clk)
    if (_065_) \mem[4] [0] <= _001_[0];
  always @(posedge clk)
    if (_065_) \mem[4] [1] <= _001_[1];
  always @(posedge clk)
    if (_065_) \mem[4] [2] <= _001_[2];
  always @(posedge clk)
    if (_065_) \mem[4] [3] <= _001_[3];
  always @(posedge clk)
    if (_065_) \mem[4] [4] <= _001_[4];
  always @(posedge clk)
    if (_065_) \mem[4] [5] <= _001_[5];
  always @(posedge clk)
    if (_065_) \mem[4] [6] <= _001_[6];
  always @(posedge clk)
    if (_065_) \mem[4] [7] <= _001_[7];
  always @(posedge clk)
    if (_061_) \mem[15] [0] <= _001_[0];
  always @(posedge clk)
    if (_061_) \mem[15] [1] <= _001_[1];
  always @(posedge clk)
    if (_061_) \mem[15] [2] <= _001_[2];
  always @(posedge clk)
    if (_061_) \mem[15] [3] <= _001_[3];
  always @(posedge clk)
    if (_061_) \mem[15] [4] <= _001_[4];
  always @(posedge clk)
    if (_061_) \mem[15] [5] <= _001_[5];
  always @(posedge clk)
    if (_061_) \mem[15] [6] <= _001_[6];
  always @(posedge clk)
    if (_061_) \mem[15] [7] <= _001_[7];
  reg \wr_ptr_reg[0]  = 1'h0;
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) \wr_ptr_reg[0]  <= 1'h0;
    else if (_005_[7]) \wr_ptr_reg[0]  <= _074_[0];
  assign wr_ptr[0] = \wr_ptr_reg[0] ;
  reg \wr_ptr_reg[1]  = 1'h0;
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) \wr_ptr_reg[1]  <= 1'h0;
    else if (_005_[7]) \wr_ptr_reg[1]  <= _075_[1];
  assign wr_ptr[1] = \wr_ptr_reg[1] ;
  reg \wr_ptr_reg[2]  = 1'h0;
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) \wr_ptr_reg[2]  <= 1'h0;
    else if (_005_[7]) \wr_ptr_reg[2]  <= _075_[2];
  assign wr_ptr[2] = \wr_ptr_reg[2] ;
  reg \wr_ptr_reg[3]  = 1'h0;
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) \wr_ptr_reg[3]  <= 1'h0;
    else if (_005_[7]) \wr_ptr_reg[3]  <= _075_[3];
  assign wr_ptr[3] = \wr_ptr_reg[3] ;
  reg \rd_ptr_reg[0]  = 1'h0;
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) \rd_ptr_reg[0]  <= 1'h0;
    else if (_040_) \rd_ptr_reg[0]  <= _080_[0];
  assign rd_ptr[0] = \rd_ptr_reg[0] ;
  reg \rd_ptr_reg[1]  = 1'h0;
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) \rd_ptr_reg[1]  <= 1'h0;
    else if (_040_) \rd_ptr_reg[1]  <= _081_[1];
  assign rd_ptr[1] = \rd_ptr_reg[1] ;
  reg \rd_ptr_reg[2]  = 1'h0;
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) \rd_ptr_reg[2]  <= 1'h0;
    else if (_040_) \rd_ptr_reg[2]  <= _081_[2];
  assign rd_ptr[2] = \rd_ptr_reg[2] ;
  reg \rd_ptr_reg[3]  = 1'h0;
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) \rd_ptr_reg[3]  <= 1'h0;
    else if (_040_) \rd_ptr_reg[3]  <= _081_[3];
  assign rd_ptr[3] = \rd_ptr_reg[3] ;
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) count[0] <= 1'h0;
    else if (_007_) count[0] <= _072_[0];
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) count[1] <= 1'h0;
    else if (_007_) count[1] <= _072_[1];
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) count[2] <= 1'h0;
    else if (_007_) count[2] <= _072_[2];
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) count[3] <= 1'h0;
    else if (_007_) count[3] <= _072_[3];
  (* src = "fifo.v:24.5-45.8" *)
  always @(posedge clk)
    if (rst) count[4] <= 1'h0;
    else if (_007_) count[4] <= _072_[4];
  always @(posedge clk)
    if (_064_) \mem[3] [0] <= _001_[0];
  always @(posedge clk)
    if (_064_) \mem[3] [1] <= _001_[1];
  always @(posedge clk)
    if (_064_) \mem[3] [2] <= _001_[2];
  always @(posedge clk)
    if (_064_) \mem[3] [3] <= _001_[3];
  always @(posedge clk)
    if (_064_) \mem[3] [4] <= _001_[4];
  always @(posedge clk)
    if (_064_) \mem[3] [5] <= _001_[5];
  always @(posedge clk)
    if (_064_) \mem[3] [6] <= _001_[6];
  always @(posedge clk)
    if (_064_) \mem[3] [7] <= _001_[7];
  always @(posedge clk)
    if (_063_) \mem[2] [0] <= _001_[0];
  always @(posedge clk)
    if (_063_) \mem[2] [1] <= _001_[1];
  always @(posedge clk)
    if (_063_) \mem[2] [2] <= _001_[2];
  always @(posedge clk)
    if (_063_) \mem[2] [3] <= _001_[3];
  always @(posedge clk)
    if (_063_) \mem[2] [4] <= _001_[4];
  always @(posedge clk)
    if (_063_) \mem[2] [5] <= _001_[5];
  always @(posedge clk)
    if (_063_) \mem[2] [6] <= _001_[6];
  always @(posedge clk)
    if (_063_) \mem[2] [7] <= _001_[7];
  always @(posedge clk)
    if (_062_) \mem[1] [0] <= _001_[0];
  always @(posedge clk)
    if (_062_) \mem[1] [1] <= _001_[1];
  always @(posedge clk)
    if (_062_) \mem[1] [2] <= _001_[2];
  always @(posedge clk)
    if (_062_) \mem[1] [3] <= _001_[3];
  always @(posedge clk)
    if (_062_) \mem[1] [4] <= _001_[4];
  always @(posedge clk)
    if (_062_) \mem[1] [5] <= _001_[5];
  always @(posedge clk)
    if (_062_) \mem[1] [6] <= _001_[6];
  always @(posedge clk)
    if (_062_) \mem[1] [7] <= _001_[7];
  always @(posedge clk)
    if (_070_) \mem[9] [0] <= _001_[0];
  always @(posedge clk)
    if (_070_) \mem[9] [1] <= _001_[1];
  always @(posedge clk)
    if (_070_) \mem[9] [2] <= _001_[2];
  always @(posedge clk)
    if (_070_) \mem[9] [3] <= _001_[3];
  always @(posedge clk)
    if (_070_) \mem[9] [4] <= _001_[4];
  always @(posedge clk)
    if (_070_) \mem[9] [5] <= _001_[5];
  always @(posedge clk)
    if (_070_) \mem[9] [6] <= _001_[6];
  always @(posedge clk)
    if (_070_) \mem[9] [7] <= _001_[7];
  assign _077_[0] = ~count[0];
  assign _074_[0] = ~wr_ptr[0];
  assign _083_[1] = ~count[1];
  assign _083_[2] = ~count[2];
  assign _083_[3] = ~count[3];
  assign _083_[4] = ~count[4];
  assign _080_[0] = ~rd_ptr[0];
  assign _039_ = _037_ |(* src = "fifo.v:21.20-21.34" *)  _083_[4];
  assign _007_ = _005_[7] | _040_;
  assign _036_[0] = count[0] |(* src = "fifo.v:22.21-22.31" *)  count[1];
  assign _036_[1] = count[2] |(* src = "fifo.v:22.21-22.31" *)  count[3];
  assign _037_ = _036_[0] |(* src = "fifo.v:22.21-22.31" *)  _036_[1];
  assign _038_ = _037_ |(* src = "fifo.v:22.21-22.31" *)  count[4];
  assign full = ~(* src = "fifo.v:21.20-21.34" *) _039_;
  assign empty = ~(* src = "fifo.v:22.21-22.31" *) _038_;
  assign _005_[7] = wr_en &(* src = "fifo.v:32.17-32.31" *)  _039_;
  assign _040_ = rd_en &(* src = "fifo.v:39.17-39.32" *)  _038_;
  assign _001_[0] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _004_[0];
  assign _001_[1] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _004_[1];
  assign _001_[2] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _004_[2];
  assign _001_[3] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _004_[3];
  assign _001_[4] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _004_[4];
  assign _001_[5] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _004_[5];
  assign _001_[6] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _004_[6];
  assign _001_[7] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _004_[7];
  assign _046_[0] = rd_ptr[1] ? _054_[0] : _053_[0];
  assign _046_[1] = rd_ptr[1] ? _054_[1] : _053_[1];
  assign _046_[2] = rd_ptr[1] ? _054_[2] : _053_[2];
  assign _046_[3] = rd_ptr[1] ? _054_[3] : _053_[3];
  assign _046_[4] = rd_ptr[1] ? _054_[4] : _053_[4];
  assign _046_[5] = rd_ptr[1] ? _054_[5] : _053_[5];
  assign _046_[6] = rd_ptr[1] ? _054_[6] : _053_[6];
  assign _046_[7] = rd_ptr[1] ? _054_[7] : _053_[7];
  assign _003_[0] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) wr_ptr[0] : 1'hx;
  assign _003_[1] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) wr_ptr[1] : 1'hx;
  assign _003_[2] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) wr_ptr[2] : 1'hx;
  assign _003_[3] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) wr_ptr[3] : 1'hx;
  assign _045_[0] = rd_ptr[1] ? _052_[0] : _051_[0];
  assign _045_[1] = rd_ptr[1] ? _052_[1] : _051_[1];
  assign _045_[2] = rd_ptr[1] ? _052_[2] : _051_[2];
  assign _045_[3] = rd_ptr[1] ? _052_[3] : _051_[3];
  assign _045_[4] = rd_ptr[1] ? _052_[4] : _051_[4];
  assign _045_[5] = rd_ptr[1] ? _052_[5] : _051_[5];
  assign _045_[6] = rd_ptr[1] ? _052_[6] : _051_[6];
  assign _045_[7] = rd_ptr[1] ? _052_[7] : _051_[7];
  assign _044_[0] = rd_ptr[1] ? _050_[0] : _049_[0];
  assign _044_[1] = rd_ptr[1] ? _050_[1] : _049_[1];
  assign _044_[2] = rd_ptr[1] ? _050_[2] : _049_[2];
  assign _044_[3] = rd_ptr[1] ? _050_[3] : _049_[3];
  assign _044_[4] = rd_ptr[1] ? _050_[4] : _049_[4];
  assign _044_[5] = rd_ptr[1] ? _050_[5] : _049_[5];
  assign _044_[6] = rd_ptr[1] ? _050_[6] : _049_[6];
  assign _044_[7] = rd_ptr[1] ? _050_[7] : _049_[7];
  assign _004_[0] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) data_in[0] : 1'hx;
  assign _004_[1] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) data_in[1] : 1'hx;
  assign _004_[2] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) data_in[2] : 1'hx;
  assign _004_[3] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) data_in[3] : 1'hx;
  assign _004_[4] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) data_in[4] : 1'hx;
  assign _004_[5] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) data_in[5] : 1'hx;
  assign _004_[6] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) data_in[6] : 1'hx;
  assign _004_[7] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) data_in[7] : 1'hx;
  assign _002_[7] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'h0 : _005_[7];
  assign _043_[0] = rd_ptr[1] ? _048_[0] : _047_[0];
  assign _043_[1] = rd_ptr[1] ? _048_[1] : _047_[1];
  assign _043_[2] = rd_ptr[1] ? _048_[2] : _047_[2];
  assign _043_[3] = rd_ptr[1] ? _048_[3] : _047_[3];
  assign _043_[4] = rd_ptr[1] ? _048_[4] : _047_[4];
  assign _043_[5] = rd_ptr[1] ? _048_[5] : _047_[5];
  assign _043_[6] = rd_ptr[1] ? _048_[6] : _047_[6];
  assign _043_[7] = rd_ptr[1] ? _048_[7] : _047_[7];
  assign _000_[0] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _003_[0];
  assign _000_[1] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _003_[1];
  assign _000_[2] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _003_[2];
  assign _000_[3] = rst ? (* src = "fifo.v:25.13-25.16|fifo.v:25.9-44.12" *) 1'hx : _003_[3];
  assign _071_[0] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) _077_[0] : 1'hx;
  assign _071_[1] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) _078_[1] : 1'hx;
  assign _071_[2] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) _078_[2] : 1'hx;
  assign _071_[3] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) _078_[3] : 1'hx;
  assign _071_[4] = _005_[7] ? (* src = "fifo.v:32.17-32.31|fifo.v:32.13-36.16" *) _078_[4] : 1'hx;
  assign _072_[0] = _040_ ? (* src = "fifo.v:39.17-39.32|fifo.v:39.13-43.16" *) _077_[0] : _071_[0];
  assign _072_[1] = _040_ ? (* src = "fifo.v:39.17-39.32|fifo.v:39.13-43.16" *) _084_[1] : _071_[1];
  assign _072_[2] = _040_ ? (* src = "fifo.v:39.17-39.32|fifo.v:39.13-43.16" *) _084_[2] : _071_[2];
  assign _072_[3] = _040_ ? (* src = "fifo.v:39.17-39.32|fifo.v:39.13-43.16" *) _084_[3] : _071_[3];
  assign _072_[4] = _040_ ? (* src = "fifo.v:39.17-39.32|fifo.v:39.13-43.16" *) _084_[4] : _071_[4];
  assign _054_[0] = rd_ptr[0] ? \mem[15] [0] : \mem[14] [0];
  assign _054_[1] = rd_ptr[0] ? \mem[15] [1] : \mem[14] [1];
  assign _054_[2] = rd_ptr[0] ? \mem[15] [2] : \mem[14] [2];
  assign _054_[3] = rd_ptr[0] ? \mem[15] [3] : \mem[14] [3];
  assign _054_[4] = rd_ptr[0] ? \mem[15] [4] : \mem[14] [4];
  assign _054_[5] = rd_ptr[0] ? \mem[15] [5] : \mem[14] [5];
  assign _054_[6] = rd_ptr[0] ? \mem[15] [6] : \mem[14] [6];
  assign _054_[7] = rd_ptr[0] ? \mem[15] [7] : \mem[14] [7];
  assign _053_[0] = rd_ptr[0] ? \mem[13] [0] : \mem[12] [0];
  assign _053_[1] = rd_ptr[0] ? \mem[13] [1] : \mem[12] [1];
  assign _053_[2] = rd_ptr[0] ? \mem[13] [2] : \mem[12] [2];
  assign _053_[3] = rd_ptr[0] ? \mem[13] [3] : \mem[12] [3];
  assign _053_[4] = rd_ptr[0] ? \mem[13] [4] : \mem[12] [4];
  assign _053_[5] = rd_ptr[0] ? \mem[13] [5] : \mem[12] [5];
  assign _053_[6] = rd_ptr[0] ? \mem[13] [6] : \mem[12] [6];
  assign _053_[7] = rd_ptr[0] ? \mem[13] [7] : \mem[12] [7];
  assign _052_[0] = rd_ptr[0] ? \mem[11] [0] : \mem[10] [0];
  assign _052_[1] = rd_ptr[0] ? \mem[11] [1] : \mem[10] [1];
  assign _052_[2] = rd_ptr[0] ? \mem[11] [2] : \mem[10] [2];
  assign _052_[3] = rd_ptr[0] ? \mem[11] [3] : \mem[10] [3];
  assign _052_[4] = rd_ptr[0] ? \mem[11] [4] : \mem[10] [4];
  assign _052_[5] = rd_ptr[0] ? \mem[11] [5] : \mem[10] [5];
  assign _052_[6] = rd_ptr[0] ? \mem[11] [6] : \mem[10] [6];
  assign _052_[7] = rd_ptr[0] ? \mem[11] [7] : \mem[10] [7];
  assign _051_[0] = rd_ptr[0] ? \mem[9] [0] : \mem[8] [0];
  assign _051_[1] = rd_ptr[0] ? \mem[9] [1] : \mem[8] [1];
  assign _051_[2] = rd_ptr[0] ? \mem[9] [2] : \mem[8] [2];
  assign _051_[3] = rd_ptr[0] ? \mem[9] [3] : \mem[8] [3];
  assign _051_[4] = rd_ptr[0] ? \mem[9] [4] : \mem[8] [4];
  assign _051_[5] = rd_ptr[0] ? \mem[9] [5] : \mem[8] [5];
  assign _051_[6] = rd_ptr[0] ? \mem[9] [6] : \mem[8] [6];
  assign _051_[7] = rd_ptr[0] ? \mem[9] [7] : \mem[8] [7];
  assign _042_[0] = rd_ptr[2] ? _046_[0] : _045_[0];
  assign _042_[1] = rd_ptr[2] ? _046_[1] : _045_[1];
  assign _042_[2] = rd_ptr[2] ? _046_[2] : _045_[2];
  assign _042_[3] = rd_ptr[2] ? _046_[3] : _045_[3];
  assign _042_[4] = rd_ptr[2] ? _046_[4] : _045_[4];
  assign _042_[5] = rd_ptr[2] ? _046_[5] : _045_[5];
  assign _042_[6] = rd_ptr[2] ? _046_[6] : _045_[6];
  assign _042_[7] = rd_ptr[2] ? _046_[7] : _045_[7];
  assign _041_[0] = rd_ptr[2] ? _044_[0] : _043_[0];
  assign _041_[1] = rd_ptr[2] ? _044_[1] : _043_[1];
  assign _041_[2] = rd_ptr[2] ? _044_[2] : _043_[2];
  assign _041_[3] = rd_ptr[2] ? _044_[3] : _043_[3];
  assign _041_[4] = rd_ptr[2] ? _044_[4] : _043_[4];
  assign _041_[5] = rd_ptr[2] ? _044_[5] : _043_[5];
  assign _041_[6] = rd_ptr[2] ? _044_[6] : _043_[6];
  assign _041_[7] = rd_ptr[2] ? _044_[7] : _043_[7];
  assign _050_[0] = rd_ptr[0] ? \mem[7] [0] : \mem[6] [0];
  assign _050_[1] = rd_ptr[0] ? \mem[7] [1] : \mem[6] [1];
  assign _050_[2] = rd_ptr[0] ? \mem[7] [2] : \mem[6] [2];
  assign _050_[3] = rd_ptr[0] ? \mem[7] [3] : \mem[6] [3];
  assign _050_[4] = rd_ptr[0] ? \mem[7] [4] : \mem[6] [4];
  assign _050_[5] = rd_ptr[0] ? \mem[7] [5] : \mem[6] [5];
  assign _050_[6] = rd_ptr[0] ? \mem[7] [6] : \mem[6] [6];
  assign _050_[7] = rd_ptr[0] ? \mem[7] [7] : \mem[6] [7];
  assign _006_[0] = rd_ptr[3] ? _042_[0] : _041_[0];
  assign _006_[1] = rd_ptr[3] ? _042_[1] : _041_[1];
  assign _006_[2] = rd_ptr[3] ? _042_[2] : _041_[2];
  assign _006_[3] = rd_ptr[3] ? _042_[3] : _041_[3];
  assign _006_[4] = rd_ptr[3] ? _042_[4] : _041_[4];
  assign _006_[5] = rd_ptr[3] ? _042_[5] : _041_[5];
  assign _006_[6] = rd_ptr[3] ? _042_[6] : _041_[6];
  assign _006_[7] = rd_ptr[3] ? _042_[7] : _041_[7];
  assign _049_[0] = rd_ptr[0] ? \mem[5] [0] : \mem[4] [0];
  assign _049_[1] = rd_ptr[0] ? \mem[5] [1] : \mem[4] [1];
  assign _049_[2] = rd_ptr[0] ? \mem[5] [2] : \mem[4] [2];
  assign _049_[3] = rd_ptr[0] ? \mem[5] [3] : \mem[4] [3];
  assign _049_[4] = rd_ptr[0] ? \mem[5] [4] : \mem[4] [4];
  assign _049_[5] = rd_ptr[0] ? \mem[5] [5] : \mem[4] [5];
  assign _049_[6] = rd_ptr[0] ? \mem[5] [6] : \mem[4] [6];
  assign _049_[7] = rd_ptr[0] ? \mem[5] [7] : \mem[4] [7];
  assign _048_[0] = rd_ptr[0] ? \mem[3] [0] : \mem[2] [0];
  assign _048_[1] = rd_ptr[0] ? \mem[3] [1] : \mem[2] [1];
  assign _048_[2] = rd_ptr[0] ? \mem[3] [2] : \mem[2] [2];
  assign _048_[3] = rd_ptr[0] ? \mem[3] [3] : \mem[2] [3];
  assign _048_[4] = rd_ptr[0] ? \mem[3] [4] : \mem[2] [4];
  assign _048_[5] = rd_ptr[0] ? \mem[3] [5] : \mem[2] [5];
  assign _048_[6] = rd_ptr[0] ? \mem[3] [6] : \mem[2] [6];
  assign _048_[7] = rd_ptr[0] ? \mem[3] [7] : \mem[2] [7];
  assign _047_[0] = rd_ptr[0] ? \mem[1] [0] : \mem[0] [0];
  assign _047_[1] = rd_ptr[0] ? \mem[1] [1] : \mem[0] [1];
  assign _047_[2] = rd_ptr[0] ? \mem[1] [2] : \mem[0] [2];
  assign _047_[3] = rd_ptr[0] ? \mem[1] [3] : \mem[0] [3];
  assign _047_[4] = rd_ptr[0] ? \mem[1] [4] : \mem[0] [4];
  assign _047_[5] = rd_ptr[0] ? \mem[1] [5] : \mem[0] [5];
  assign _047_[6] = rd_ptr[0] ? \mem[1] [6] : \mem[0] [6];
  assign _047_[7] = rd_ptr[0] ? \mem[1] [7] : \mem[0] [7];
  assign _034_ = ~_000_[2];
  assign _035_ = ~_000_[3];
  assign _033_ = ~_000_[1];
  assign _032_ = ~_000_[0];
  assign _078_[1] = count[1] ^(* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  count[0];
  assign _078_[2] = count[2] ^(* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _076_[1];
  assign _078_[3] = count[3] ^(* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _076_[2];
  assign _078_[4] = count[4] ^(* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _076_[3];
  assign _081_[1] = rd_ptr[1] ^(* src = "fifo.v:41.27-41.37|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  rd_ptr[0];
  assign _081_[2] = rd_ptr[2] ^(* src = "fifo.v:41.27-41.37|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _079_[1];
  assign _081_[3] = rd_ptr[3] ^(* src = "fifo.v:41.27-41.37|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _079_[2];
  assign _084_[1] = _083_[1] ^(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  count[0];
  assign _084_[2] = _083_[2] ^(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _082_[1];
  assign _084_[3] = _083_[3] ^(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _082_[2];
  assign _084_[4] = _083_[4] ^(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _082_[3];
  assign _073_[1] = wr_ptr[1] &(* src = "fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  wr_ptr[0];
  assign _073_[2] = wr_ptr[2] &(* src = "fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _073_[1];
  assign _076_[1] = count[1] &(* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[0];
  assign _076_[3] = _085_ &(* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _076_[1];
  assign _085_ = count[3] &(* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  count[2];
  assign _076_[2] = count[2] &(* src = "fifo.v:35.26-35.35|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _076_[1];
  assign _079_[1] = rd_ptr[1] &(* src = "fifo.v:41.27-41.37|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  rd_ptr[0];
  assign _079_[2] = rd_ptr[2] &(* src = "fifo.v:41.27-41.37|fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _079_[1];
  assign _086_ = _083_[1] &(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[0];
  assign _087_ = _083_[3] &(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  count[2];
  assign _088_ = _089_ &(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.19-240.41" *)  _082_[1];
  assign _089_ = _083_[3] &(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:241.12-241.34" *)  _083_[2];
  assign _090_ = _083_[2] &(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.19-248.41" *)  _082_[1];
  assign _082_[1] = count[1] |(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _086_;
  assign _091_ = count[3] |(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _087_;
  assign _082_[3] = _091_ |(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:240.12-240.41" *)  _088_;
  assign _082_[2] = count[2] |(* src = "fifo.v:42.26-42.35|/usr/local/bin/../share/yosys/techmap.v:286.27-286.69|/usr/local/bin/../share/yosys/techmap.v:248.12-248.41" *)  _090_;
  assign _009_ = _034_ & _035_;
  assign _010_ = _008_ & _009_;
  assign _055_ = _010_ & _002_[7];
  assign _011_ = _000_[0] & _033_;
  assign _063_ = _014_ & _002_[7];
  assign _014_ = _013_ & _009_;
  assign _013_ = _032_ & _000_[1];
  assign _062_ = _012_ & _002_[7];
  assign _012_ = _011_ & _009_;
  assign _008_ = _032_ & _033_;
  assign _064_ = _016_ & _002_[7];
  assign _016_ = _015_ & _009_;
  assign _015_ = _000_[0] & _000_[1];
  assign _017_ = _000_[2] & _035_;
  assign _018_ = _008_ & _017_;
  assign _065_ = _018_ & _002_[7];
  assign _019_ = _011_ & _017_;
  assign _066_ = _019_ & _002_[7];
  assign _020_ = _013_ & _017_;
  assign _067_ = _020_ & _002_[7];
  assign _021_ = _015_ & _017_;
  assign _068_ = _021_ & _002_[7];
  assign _022_ = _034_ & _000_[3];
  assign _023_ = _008_ & _022_;
  assign _069_ = _023_ & _002_[7];
  assign _024_ = _011_ & _022_;
  assign _070_ = _024_ & _002_[7];
  assign _025_ = _013_ & _022_;
  assign _056_ = _025_ & _002_[7];
  assign _026_ = _015_ & _022_;
  assign _057_ = _026_ & _002_[7];
  assign _027_ = _000_[2] & _000_[3];
  assign _028_ = _008_ & _027_;
  assign _058_ = _028_ & _002_[7];
  assign _029_ = _011_ & _027_;
  assign _059_ = _029_ & _002_[7];
  assign _030_ = _013_ & _027_;
  assign _060_ = _030_ & _002_[7];
  assign _031_ = _015_ & _027_;
  assign _061_ = _031_ & _002_[7];
  assign _075_[1] = wr_ptr[1] ^(* src = "fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  wr_ptr[0];
  assign _075_[2] = wr_ptr[2] ^(* src = "fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _073_[1];
  assign _075_[3] = wr_ptr[3] ^(* src = "fifo.v:34.27-34.37|/usr/local/bin/../share/yosys/techmap.v:289.13-289.25" *)  _073_[2];
  assign _002_[6:0] = { _002_[7], _002_[7], _002_[7], _002_[7], _002_[7], _002_[7], _002_[7] };
  assign _005_[6:0] = { _005_[7], _005_[7], _005_[7], _005_[7], _005_[7], _005_[7], _005_[7] };
  assign { _073_[31:5], _073_[0] } = { 27'h0000000, wr_ptr[0] };
  assign _074_[31:1] = { 27'h0000000, wr_ptr[4:1] };
  assign { _075_[31:5], _075_[0] } = { 26'h0000000, _073_[4], _074_[0] };
  assign { _076_[31:5], _076_[0] } = { 27'h0000000, count[0] };
  assign _077_[31:1] = { 27'h0000000, count[4:1] };
  assign { _078_[31:5], _078_[0] } = { 26'h0000000, _076_[4], _077_[0] };
  assign { _079_[31:5], _079_[0] } = { 27'h0000000, rd_ptr[0] };
  assign _080_[31:1] = { 27'h0000000, rd_ptr[4:1] };
  assign { _081_[31:5], _081_[0] } = { 26'h0000000, _079_[4], _080_[0] };
  assign { _082_[30:4], _082_[0] } = { _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], _082_[31], count[0] };
  assign { _083_[31:5], _083_[0] } = { 27'h7ffffff, count[0] };
  assign { _084_[30:5], _084_[0] } = { _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _084_[31], _077_[0] };
endmodule

(* top =  1  *)
(* src = "uart_transmitter.v:1.1-40.10" *)
module uart_transmitter(clk, rst, data_in, data_valid, tx_ready, serial_out, fifo_full, tx_busy);
  (* src = "uart_transmitter.v:4.11-4.14" *)
  input clk;
  wire clk;
  (* src = "uart_transmitter.v:6.17-6.24" *)
  input [7:0] data_in;
  wire [7:0] data_in;
  (* src = "uart_transmitter.v:7.11-7.21" *)
  input data_valid;
  wire data_valid;
  (* src = "uart_transmitter.v:15.16-15.25" *)
  wire [7:0] fifo_data;
  (* src = "uart_transmitter.v:14.10-14.20" *)
  wire fifo_empty;
  (* src = "uart_transmitter.v:10.12-10.21" *)
  output fifo_full;
  wire fifo_full;
  (* src = "uart_transmitter.v:16.10-16.15" *)
  wire rd_en;
  (* src = "uart_transmitter.v:5.11-5.14" *)
  input rst;
  wire rst;
  (* src = "uart_transmitter.v:9.12-9.22" *)
  output serial_out;
  wire serial_out;
  (* src = "uart_transmitter.v:11.12-11.19" *)
  output tx_busy;
  wire tx_busy;
  (* src = "uart_transmitter.v:8.11-8.19" *)
  input tx_ready;
  wire tx_ready;
  (* module_not_derived = 32'd1 *)
  (* src = "uart_transmitter.v:18.10-27.6" *)
  fifo u_fifo (
    .clk(clk),
    .data_in(data_in),
    .data_out(fifo_data),
    .empty(fifo_empty),
    .full(fifo_full),
    .rd_en(rd_en),
    .rst(rst),
    .wr_en(data_valid)
  );
  (* src = "uart_transmitter.v:29.36-38.6" *)
  \$paramod\packetizer_fsm\BAUD_DIVISOR=s32'00000000000000000000000000000101  u_fsm (
    .clk(clk),
    .fifo_data(fifo_data),
    .fifo_empty(fifo_empty),
    .rd_en(rd_en),
    .rst(rst),
    .serial_out(serial_out),
    .tx_busy(tx_busy),
    .tx_ready(tx_ready)
  );
endmodule
